// Single re-export point for the Wails bridge surface.
//
// MUST stay a sibling of main.tsx: the vite plugin in vite.config.js
// substitutes the test harnesses (wails-mock.ts / wails-bridge.ts) by
// matching the EXACT literal specifiers '../wailsjs/go/main/App' and
// '../wailsjs/runtime/runtime' — moving this file changes the relative
// specifier and silently breaks both Playwright harnesses.
//
// Explicit named re-exports (no `export *`): under substitution both
// specifiers resolve to ONE module, and star-re-exporting the same
// names from two paths would make them ambiguous (ES modules silently
// drop ambiguous star exports).

export {
  ConnectControl,
  OpenSession,
  CloseAttach,
  WriteStdin,
  ResizeSession,
  RequestScrollbackReplay,
  CreateSession,
  DuplicateSession,
  KillSession,
  KillSessionAndWorktree,
  RestartSession,
  RestoreSession,
  ListClosedSessions,
  UpdateSession,
  SetSessionAttention,
  GetActivity,
  SearchTranscript,
  GetTranscriptLines,
  ListAgents,
  ListCustomAgents,
  SaveCustomAgents,
  GetAgentSettings,
  SaveAgentSettings,
  CreateProject,
  KillProject,
  UpdateProject,
  ListIdeas,
  AddIdea,
  UpdateIdea,
  RemoveIdea,
  ListPlugins,
  InstallPlugin,
  SetPluginEnabled,
  RemovePlugin,
  ResolvePrompt,
  ResolveWorktreeChoice,
  GetPlanReview,
  ResolvePlanReview,
  GetExternalPlanReviewers,
  ListWorktrees,
  RemoveWorktree,
  CreateWorktree,
  RenameWorktree,
  SetWorktreeLabel,
  DeleteBranch,
  LaunchDir,
  StateDirID,
  PickDirectory,
  OpenNewWindow,
  CloseWindow,
  IsGitRepo,
  OpenURL,
  OpenTerminalAt,
  ResolveFilePaths,
  OpenFile,
  GetEditorSettings,
  SaveEditorSettings,
  Notify,
  Confirm,
  RestartDaemon,
  ReloadGUI,
  RequestReloadAllGUIs,
  CheckForUpdate,
  UpdateStatus,
  StartUpdate,
  UpdateBuildLog,
  ApplyUpdateAndRestart,
  GetUpdateSettings,
  SaveUpdateSettings,
  SourceRepoStatusFor,
  SetClipboardText,
  LogFrontend,
  SetDebugTrace,
  MenuBarLoginItemStatus,
  SetMenuBarLoginItem,
} from '../wailsjs/go/main/App';
export {
  EventsOn,
  WindowSetTitle,
  ClipboardGetText,
} from '../wailsjs/runtime/runtime';
