// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Resize(arg1, arg2) {
  return window['go']['main']['App']['Resize'](arg1, arg2);
}

export function StartShell(arg1, arg2) {
  return window['go']['main']['App']['StartShell'](arg1, arg2);
}

export function WriteStdin(arg1) {
  return window['go']['main']['App']['WriteStdin'](arg1);
}
